spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show:sql: true
        format_sql: true

        #이런 설정들은 springboot 오피셜 페이지 메뉴얼 보고 하나하나 공부해야함
        #엄청 많음,,

  logging:
    level:
      org.hibernate.SQL: debug
      #hibernate이 생성하는 sql들을 디버그 모드로 로그로 찍음